# Generated by Django 5.0.14 on 2025-07-19 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admit_id', models.CharField(max_length=32)),
                ('icd10_code', models.CharField(max_length=32)),
                ('encounter', models.CharField(max_length=64)),
                ('service_code', models.CharField(max_length=64)),
                ('quantity', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('service_id', models.CharField(max_length=32)),
                ('benefit', models.CharField(max_length=128)),
                ('benefit_desc', models.CharField(max_length=256)),
                ('claim_prov_date', models.CharField(max_length=32)),
                ('claim_pod', models.CharField(max_length=16)),
                ('dob', models.CharField(max_length=32)),
                ('gender', models.CharField(max_length=8)),
                ('dependent_type', models.CharField(max_length=32)),
                ('ailment', models.CharField(max_length=128)),
                ('claim_me', models.CharField(max_length=64)),
                ('claim_ce', models.CharField(max_length=64)),
                ('claim_in_global', models.CharField(max_length=64)),
                ('claim_pa', models.CharField(max_length=64)),
                ('claim_pr', models.CharField(max_length=64)),
                ('prov_name', models.CharField(max_length=128)),
                ('pol_id', models.CharField(max_length=32)),
                ('pol_name', models.CharField(max_length=128)),
                ('cost_center', models.CharField(max_length=128)),
            ],
        ),
    ]
