# Generated by Django 5.0.14 on 2025-07-23 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_userprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claimrecord',
            name='claim_prov_date',
            field=models.DateField(max_length=32),
        ),
        migrations.AlterField(
            model_name='claimrecord',
            name='dob',
            field=models.DateField(max_length=32),
        ),
    ]
