# Generated by Django 5.0.14 on 2025-07-23 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_claimrecord_claim_prov_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='claimrecord',
            options={'ordering': ['-claim_prov_date'], 'verbose_name': 'Claim Record', 'verbose_name_plural': 'Claim Records'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'User Profile', 'verbose_name_plural': 'User Profiles'},
        ),
        migrations.AlterField(
            model_name='claimrecord',
            name='claim_prov_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='claimrecord',
            name='dob',
            field=models.DateField(),
        ),
    ]
